"""Closed CURIE contract constants. Criterion names must match the wire exactly."""

CURIE_CRITERION_TASK_RELEVANCE = "Task Relevance"
CURIE_CRITERION_REASONING = "Reasoning / Understanding"
CURIE_CRITERION_SPECIFICITY = "Specificity & Evidence"

CURIE_CRITERIA = (
    CURIE_CRITERION_TASK_RELEVANCE,
    CURIE_CRITERION_REASONING,
    CURIE_CRITERION_SPECIFICITY,
)

RUBRIC_CATEGORY_BY_CURIE_CRITERION = {
    CURIE_CRITERION_TASK_RELEVANCE: "Task Relevance",
    CURIE_CRITERION_REASONING: "Reasoning/Understanding",
    CURIE_CRITERION_SPECIFICITY: "Specificity/Evidence",
}

RESULT_SUCCESS = "success"
RESULT_ERROR = "error"

STATUS_PENDING_EVALUATION = "pending_evaluation"
STATUS_READY = "ready"
STATUS_FAILED = "failed"

VERDICT_ACCEPTED = "accepted"
VERDICT_REJECTED = "rejected"

SOURCE_HUMAN = "human"
SOURCE_CURIE = "curie"

ORIGIN_TAS = "tas"
ASSIGNMENT_TYPE_SWOT = "swot"

DEFAULT_COMPONENT_PASS_THRESHOLD = 6.0
DEFAULT_SLOW_REVIEW_SECONDS = 300
DEFAULT_MAX_WAIT_SECONDS = 1800
DEFAULT_CONNECT_TIMEOUT_SECONDS = 3
DEFAULT_RESPONSE_TIMEOUT_SECONDS = 10
MAX_SUBMISSION_ATTEMPTS = 10

FIELD_COLOR_NEEDS_REVISION = "needs_revision"
FIELD_COLOR_COULD_IMPROVE = "could_improve"
FIELD_COLOR_GOOD = "good"

TIMEOUT_ERROR_DETAIL = "No response from CURIE within the maximum wait window."
TRIGGER_EXHAUSTED_ERROR_DETAIL = "CURIE trigger retries exhausted."
HUMAN_SUPERSEDED_DETAIL = "CURIE callback acknowledged but not applied: human owns the projection."
LEARNER_FAILURE_DETAIL = "CURIE could not complete this review. Please try again."

TRIGGER_RETRY_COUNTDOWNS = (15, 60, 240)
TRIGGER_RETRY_JITTER_RATIO = 0.2

ELIGIBLE_ASSIGNMENT_TYPES = frozenset({ASSIGNMENT_TYPE_SWOT})
