# Generated by Django 5.2.7 on 2026-03-11 03:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Short, human-readable name of the template type (e.g., 'Case Study').",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Short unique identifier for referencing the template type (e.g., 'essay').",
                        max_length=75,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Extended description of the template type."),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Small icon displayed in UI for this template type.",
                        null=True,
                        upload_to="tas/templates/icons/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Set False to disable this template type everywhere it is referenced."
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Type",
                "verbose_name_plural": "Template Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "course_key",
                    opaque_keys.edx.django.models.CourseKeyField(
                        db_index=True, help_text="Open edX course key in which this submission occurs.", max_length=255
                    ),
                ),
                (
                    "usage_key",
                    opaque_keys.edx.django.models.UsageKeyField(
                        db_index=True,
                        help_text="XBlock usage key for the unit where this submission is relevant.",
                        max_length=255,
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(default=dict, help_text="Current field/response data submitted by the student."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        db_index=True,
                        default="draft",
                        help_text="Current status—either draft or submitted.",
                        max_length=20,
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number of the current submission. Increments on each save."
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when student finalized this submission (moved to 'submitted').",
                        null=True,
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        help_text="Path to the generated PDF, if any.",
                        null=True,
                        upload_to="tas/submissions/pdfs/",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Reference to submitting student (Open edX user).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tas_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TAS Submission",
                "verbose_name_plural": "TAS Submissions",
                "ordering": ["-created"],
                "unique_together": {("student", "course_key", "usage_key")},
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Template display name (should be unique per template type).",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Optional description of the template."),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Background image for the template.",
                        null=True,
                        upload_to="tas/templates/images/",
                    ),
                ),
                ("image_width", models.PositiveIntegerField(help_text="Pixel width of the background image used.")),
                ("image_height", models.PositiveIntegerField(help_text="Pixel height of the background image used.")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image for the template.",
                        null=True,
                        upload_to="tas/templates/thumbnails/",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        default=list,
                        help_text="Serialized definition of dynamic form fields tied to this template. Each entry is a dict with field attributes.",
                    ),
                ),
                (
                    "field_positions",
                    models.JSONField(
                        default=dict, help_text="Map of field keys to their layout positions on the template image."
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="When True, template is available to all users (otherwise permission-based).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Inactive templates are hidden from user-facing views."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created/owns the template.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_type",
                    models.ForeignKey(
                        help_text="The type/category this template belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="tas_app.templatetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "TAS Template",
                "verbose_name_plural": "TAS Templates",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionVersion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Snapshot's version number (matches value on the Submission at save time)."
                    ),
                ),
                ("form_data", models.JSONField(help_text="Immutable snapshot of the form data for this version.")),
                (
                    "saved_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this version was created."),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Parent reference to the editable submission.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tas_submission_versions",
                        to="tas_app.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "TAS Submission Version",
                "verbose_name_plural": "TAS Submission Versions",
                "ordering": ["-version_number"],
                "unique_together": {("submission", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="TemplateBlock",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "usage_key",
                    opaque_keys.edx.django.models.UsageKeyField(
                        db_index=True, help_text="Opaque key identifying the Open edX XBlock unit.", max_length=255
                    ),
                ),
                (
                    "course_key",
                    opaque_keys.edx.django.models.CourseKeyField(
                        db_index=True, help_text="Opaque key identifying the Open edX course.", max_length=255
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Defines the order in which templates are rendered within a unit."
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp for when the template was assigned to the block."
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Identifier for the user who performed the assignment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Reference to the TAS template used in this block.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_blocks",
                        to="tas_app.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "TAS Template Block",
                "verbose_name_plural": "TAS Template Blocks",
                "ordering": ["sort_order"],
                "indexes": [
                    models.Index(fields=["usage_key", "course_key"], name="tas_app_tem_usage_k_cc1881_idx"),
                    models.Index(fields=["template", "course_key"], name="tas_app_tem_templat_605c5d_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["template_type", "is_public", "is_active"], name="tas_app_tem_templat_867298_idx"
            ),
        ),
    ]
