# Generated by Django 5.2.7 on 2026-04-12 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tas_app", "0003_instructorfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instructorfeedback",
            options={
                "ordering": ["-created"],
                "verbose_name": "Instructor Feedback",
                "verbose_name_plural": "Instructor Feedbacks",
            },
        ),
        migrations.RemoveField(
            model_name="templateblock",
            name="template_type",
        ),
        migrations.AlterField(
            model_name="instructorfeedback",
            name="comment",
            field=models.TextField(blank=True, help_text="Free-form instructor comments about the submission."),
        ),
        migrations.AlterField(
            model_name="instructorfeedback",
            name="instructor",
            field=models.ForeignKey(
                help_text="Instructor who provided this feedback.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="instructorfeedback",
            name="rubrics",
            field=models.JSONField(
                blank=True, default=list, help_text="Rubric items, ratings, or scores as structured data."
            ),
        ),
        migrations.AlterField(
            model_name="instructorfeedback",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                db_index=True,
                default="pending",
                help_text="Current feedback status: pending, approved, or rejected.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="instructorfeedback",
            name="submission",
            field=models.OneToOneField(
                help_text="The student submission this feedback belongs to. One-to-one relationship.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="tas_app.submission",
            ),
        ),
    ]
