# Generated by Django 5.2.7 on 2026-04-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tas_app", "0004_alter_instructorfeedback_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="template_block",
            field=models.ForeignKey(
                default=1,
                help_text="Reference to the template block this submission belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="tas_app.templateblock",
            ),
            preserve_default=False,
        ),
    ]
