# Generated by Django 5.2.7 on 2026-04-16 08:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tas_app", "0005_submission_template_block"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionversion",
            name="pdf",
            field=models.FileField(
                blank=True, help_text="Path to the generated PDF, if any.", null=True, upload_to="tas/submissions/pdfs/"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                help_text="Current status—either draft or submitted.",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templateblock",
            unique_together={("usage_key", "course_key")},
        ),
        migrations.CreateModel(
            name="InstructorFeedbackVersion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Snapshot's version number (matches value on the InstructorFeedback at save time)."
                    ),
                ),
                (
                    "rubrics",
                    models.JSONField(
                        blank=True, default=list, help_text="Rubric items, ratings, or scores as structured data."
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Free-form instructor comments about the submission."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        db_index=True,
                        default="pending",
                        help_text="Current feedback status: pending, approved, or rejected.",
                        max_length=20,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        help_text="Instructor who provided this feedback.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_instructor_feedback_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructor_feedback",
                    models.ForeignKey(
                        help_text="Parent reference to the editable instructor feedback.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tas_instructor_feedback_versions",
                        to="tas_app.instructorfeedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "TAS Instructor Feedback Version",
                "verbose_name_plural": "TAS Instructor Feedback Versions",
                "ordering": ["-version_number"],
                "unique_together": {("instructor_feedback", "version_number")},
            },
        ),
    ]
