# Generated by Django 5.2.7 on 2026-04-25 05:03

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tas_app", "0006_submissionversion_pdf_alter_submission_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        db_index=True, help_text="Human-readable name of the rubric (e.g., 'Essay Rubric')."
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=list,
                        help_text="Structured list of rubric criteria. Each entry defines a criterion name, options, and marks.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Set False to deactivate this rubric without deleting it.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubric",
                "verbose_name_plural": "Rubrics",
                "ordering": ["name"],
            },
        ),
    ]
