# Generated by Django 5.2.7 on 2026-04-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tas_app", "0007_rubric"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templateblock",
            name="rubrics",
        ),
    ]
