# Generated by Django 5.2.7 on 2026-04-25 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tas_app", "0008_remove_templateblock_rubrics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="templateblock",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the rubric used in this block.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_blocks",
                to="tas_app.rubric",
            ),
        ),
        migrations.AlterField(
            model_name="instructorfeedback",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text="Instructor who provided this feedback.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="given_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="instructorfeedbackversion",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text="Instructor who provided this feedback.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="given_instructor_feedback_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created/owns the template.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="templateblock",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Identifier for the user who performed the assignment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
